export default function CloudMiningPlans() {
    return (
      <section className="py-16 px-4 max-w-7xl mx-auto">
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 items-start">
          {/* Left Column */}
          <div className="space-y-8">
            <h2 className="text-4xl md:text-5xl font-bold text-darkmuted">Cloud Mining Plans</h2>
  
            <div className="border border-gray-200 rounded-lg p-6 bg-white">
              <p className="text-gray-700 text-lg">
                Currently, Bitcoin miner offers several profitable cloud mining plans: One month plan, three-month plan, and
                Six-month plan, and even one year.
              </p>
            </div>
          </div>
  
          {/* Right Column */}
          <div className="space-y-6">
            <p className="text-gray-700">
              In cloud mining contracts, a customer agrees to pay a certain amount to the service provider (here, Bitcoin miner)
              in return for access to the computing power generated by the remote crypto mining center.
            </p>
  
            <p className="text-gray-700">
              Customers buy hashrate from Bitcoin mining contractors to gain online access to hashing power.
            </p>
  
            <p className="text-gray-700">
              This makes it easy for both novice and seasoned cryptocurrency miners to purchase Bitcoin mining contracts,
              as they are transparent and easy to locate.
            </p>
          </div>
        </div>
      </section>
    )
  }
  
  